[package]
name = "shank_macro"
version = "0.0.0"
description = "Shank Macro"
authors = ["Metaplex Maintainers <maintainers@metaplex.com>"]
repository = "https://github.com/metaplex-foundation/shank"
license = "Apache-2.0"
edition = "2018"

[lib]
proc-macro = true
doctest=false

[dependencies]
shank_macro_impl = { version = "0.0.0", path = "../shank-macro-impl" }
