name: Build+Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest-16-cores, windows-latest-8-cores, macos-latest]
        include:
          - os: ubuntu-latest-16-cores
            RUST: stable

          - os: windows-latest-8-cores
            RUST: stable

          - os: macos-latest
            RUST: stable

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.RUST }}

      - uses: actions/checkout@master

      - name: Build and Run Tests
        run: cargo test
